# Generated by Django 4.1.6 on 2023-02-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_remove_fotografia_foto_fotografia_foto_space_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotografia',
            name='foto_space',
        ),
        migrations.RemoveField(
            model_name='fotografia',
            name='publicada',
        ),
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('NEBULOSA', 'Nebulosa'), ('ESTRELA', 'Estrela'), ('GALÁXIA', 'Galáxia'), ('PLANETA', 'Planeta')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fotografia',
            name='foto',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
