# Generated by Django 4.1.6 on 2023-02-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_alter_fotografia_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='foto',
            field=models.ImageField(blank=True, upload_to='media/fotos/%Y/%m/%d/'),
        ),
    ]
